config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :sports, only: [:show, :index, :create]
  root :to => redirect('/sports')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :sport

  validates :name, presence: true
  validates :endorsements, presence: true
  validates :followers, presence: true
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
require 'nokogiri'
require 'open-uri'

class PlayersController < ApplicationController

  def index
  end

  def show
    @player = Player.find(params[:id])
    @player_name = @player.name.split(' ').join('+')
    # Look up this error:
    #  Errno::ENOENT (No such file or directory @ rb_sysopen - 'url')
    #
    # 'open' ain't working - throwing the above error
    # player pictures will have to wait
    #
    # base_url = open("https://www.google.com/search?q=#{@player_name}&source=lnms&tbm=isch")
    # data = Nokogiri::HTML(base_url)
    # byebug
    #
    # @pic =
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController

  def index
    get_sports
  end

  def show
    @sport = Sport.find(params[:id])
  end

  def create
    if search_players.include?(params[:search])
      @player = Player.find_by(name: select_player(search_players))
      redirect_to player_path(@player)
    else
      get_sports
      params[:error] = 'No players match that name'
      render :index
    end
  end

  private
  def get_sports
    @sports = Sport.all
  end

  def search_players
    Sport.all.map{|sport| sport.players.map(&:name)}.join(' , ')
  end

  def select_player(players)
    players.split(' , ').select{|name| name.include?(params[:search])}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Sports App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.min.css'>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/show.html.erb
<h1><%= @player.name %></h1>
<h2><%= @player.sport.name %></h2>


<%= link_to "See All #{@player.sport.name} Players", sport_path(@player.sport) %>

app/views/sports/index.html.erb
<h1>Sports App</h1>
<br>

<% if params[:error] %>
  <h4 class='error'><%= params[:error] %></h4>
<% end %>

<ul>
  <% @sports.each do |sport| %>
  <li>
    <h3><%= link_to sport.name, sport %></h3>
    First Played in <%= sport.first_played %><br>
    Players in database: <%= sport.players.count %><br>
    Total endorsements of players: $<%= sport.players.map(&:endorsements).sum.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %>
  </li>
  <% end %>
</ul>

<%= form_tag(sports_path method: :get) do %> 
  <p>Search for a Player</p>
  <%= text_field_tag :search, params[:search] %> 
  <%= submit_tag 'Search' %> 
<% end %>

app/views/sports/show.html.erb
<h1><%= @sport.name %></h1>
<h3>Average Age: <%= @sport.players.map(&:age).sum / @sport.players.count %></h3>
<br>

<ul>
  <% @sport.players.each do |player| %>
  <li>
    <h3><%= link_to player.name, player %></h3>
  </li>
  <br>
  <% end %>
</ul>

<h4>Total followers: <%= @sport.players.map(&:followers).sum.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %></h4>
<h4><%= link_to "Back to All Sports", sports_path %></h4>